name: Check Repository Vars
description: Check Repository Vars
inputs:
  repositoryName:
    description: 'Repository Name where variable needs to be checked'
    type: string
  variableName:
    description: 'Variable name to be checked'
    type: string
  isSecret:
    description: 'Flag if variable is a secret'
    type: string
    default: 'false'

runs:
  using: "composite"
  steps:  
  - name: Identify URL
    id: url
    uses: actions/github-script@v7
    with:
      script: |
        var getVarsUrl = "repos/${{ env.OWNER_NAME }}/${{ inputs.repositoryName }}/actions"
        if("${{ inputs.isSecret }}" == "true"){
          getVarsUrl = getVarsUrl + "/secrets"
        }
        else {
          getVarsUrl = getVarsUrl + "/variables"
        }
        core.setOutput("getVarsUrl", getVarsUrl)

  - name: Get Var
    id: get-var
    uses: kgacandole/github_automation_scripts/.github/actions/invokeGithubApi@main
    with:
      uriPath: "${{ steps.url.outputs.getVarsUrl }}"
      method: "GET"
      maskResponse: "true"
  
  - name: Extract Vars
    id: var-details
    uses: cloudposse/github-action-jq@main
    with:
      compact: true
      input: '${{ steps.get-var.outputs.response }}'
      raw-output: true
      script: |-
        .secrets | .[] | select(.name == "${{ inputs.variableName }}") | .name
  
  - name: Check if Vars Exist
    if: steps.var-details.outputs.output != ''
    uses: actions/github-script@v7
    with:
      script: core.setFailed("Variable already exists. Please select force update if you want to proceed.")