name: Create Repository Secrets
run-name: Create Repository Secrets - ${{ inputs.REPOSITORY_NAME }} - ${{ inputs.SECRET_NAME }}
on:
  workflow_dispatch:
    inputs:      
      REPOSITORY_NAME:
        description: 'Repository Name'
        type: string
        required: true
      SECRET_NAME:
        description: 'Secret Name'
        required: true
      SECRET_VALUE:
        description: 'Secret Value'
        required: true
      

jobs:
  create-secrets:
    name: Create Secrets
    runs-on: [ubuntu-latest]
    env:
      OWNER_NAME: kgacandole
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
    steps:
    - name: Generate GH Token
      uses: kgacandole/github_automation_scripts/.github/actions/generateGithubToken@main
    
    - name: Get Key
      id: key
      uses: kgacandole/github_automation_scripts/.github/actions/invokeGithubApi@main
      with:
        uriPath: "repos/${{ env.OWNER_NAME }}/${{ inputs.REPOSITORY_NAME }}/actions/secrets/public-key"
        method: "GET"
    
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ vars.PYTHON_VERSION }}

    - name: Install Prereq
      shell: bash
      run: pip install pynacl
    
    - name: Encrypt Var
      id: encrypt
      shell: python
      run: |
        import os
        from base64 import b64encode
        from nacl import encoding, public

        repoKey = "${{ fromJson(steps.key.outputs.response).key }}"
        repoKeyId = "${{ fromJson(steps.key.outputs.response).key_id }}"

        public_key = public.PublicKey(repoKey.encode("utf-8"), encoding.Base64Encoder())
        sealed_box = public.SealedBox(public_key)
        encrypted_val = sealed_box.encrypt("${{ inputs.SECRET_VALUE }}".encode("utf-8"))

        requestPayload = {
            "encrypted_value": b64encode(encrypted_val).decode('utf-8'),
            "key_id": repoKeyId
        }

        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
          print(f'repoKeyId=' + repoKeyId, file=fh)
          print(f'encryptedValue=' + b64encode(encrypted_val).decode('utf-8'), file=fh)
        fh.close()
    
    - name: Add/update Secret
      uses: kgacandole/github_automation_scripts/.github/actions/invokeGithubApi@main
      with:
        uriPath: "repos/${{ env.OWNER_NAME }}/${{ inputs.REPOSITORY_NAME }}/actions/secrets/${{ inputs.SECRET_NAME }}"
        method: "PUT"
        data: |
          {
            "encrypted_value": "${{ steps.encrypt.outputs.encryptedValue }}",
            "key_id": "${{ steps.encrypt.outputs.repoKeyId }}"
          }