name: Create Repository Secrets
run-name: Create Repository Secrets - ${{ inputs.REPOSITORY_NAME }} - ${{ inputs.SECRET_NAME }}
on:
  workflow_dispatch:
    inputs:      
      REPOSITORY_NAME:
        description: 'Repository Name'
        type: string
        required: true
      SECRET_NAME:
        description: 'Secret Name'
        required: true
      SECRET_VALUE:
        description: 'Secret Value'
        required: true
      

jobs:
  create-secrets:
    name: Create Secrets
    runs-on: [ubuntu-latest]
    env:
      OWNER_NAME: kgacandole
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
    steps:
    - name: Generate GH Token
      uses: kgacandole/github_automation_scripts/.github/actions/generateGithubToken@main
    
    - name: Check Secret
      uses: kgacandole/github_automation_scripts/.github/actions/checkVars@main
      with:
        repositoryName: ${{ inputs.REPOSITORY_NAME }}
        variableName: ${{ inputs.SECRET_NAME }}
        isSecret: 'true'

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: kgacandole/github_automation_scripts
        ref: main
        path: scripts
        token: ${{ env.GITHUB_TOKEN }}
    
    - name: Get Key
      id: key
      uses: kgacandole/github_automation_scripts/.github/actions/invokeGithubApi@main
      with:
        uriPath: "repos/${{ env.OWNER_NAME }}/${{ inputs.REPOSITORY_NAME }}/actions/secrets/public-key"
        method: "GET"
        maskResponse: "true"
    
    - name: Export Keys
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable("REPO_KEY", JSON.parse(JSON.stringify(${{ steps.key.outputs.response }})).key)
          core.exportVariable("REPO_KEY_ID", JSON.parse(JSON.stringify(${{ steps.key.outputs.response }})).key_id)
    
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ vars.PYTHON_VERSION }}

    - name: Install Prereq
      shell: bash
      run: pip install pynacl
    
    - name: Encrypt Var
      id: encrypt
      shell: bash
      env:
        SECRET_VALUE: ${{ inputs.SECRET_VALUE }}
      run: python scripts/python/encrypt_secret_vars.py        
    
    - name: Add/update Secret
      uses: kgacandole/github_automation_scripts/.github/actions/invokeGithubApi@main
      with:
        uriPath: "repos/${{ env.OWNER_NAME }}/${{ inputs.REPOSITORY_NAME }}/actions/secrets/${{ inputs.SECRET_NAME }}"
        method: "PUT"
        data: |
          {
            "encrypted_value": "${{ steps.encrypt.outputs.encryptedValue }}",
            "key_id": "${{ steps.encrypt.outputs.repoKeyId }}"
          }