name: Create Repository Variables
run-name: Create Repository Variables - ${{ inputs.REPOSITORY_NAME }} - ${{ inputs.VARIABLE_NAME }}
on:
  workflow_dispatch:
    inputs:
      REPOSITORY_NAME:
        description: 'Repository Name'
        type: string
        required: false
      VARIABLE_NAME:
        description: 'Variable Name'
        type: string
        required: false
      VARIABLE_VALUE:
        description: 'Variable Value'
        type: string
        required: false
      FORCE_UPDATE:
        description: 'Force Update'
        type: boolean
        default: false

jobs:
  create-vars:
    name: Create Repository Variables
    runs-on: [ubuntu-latest]
    env:
      OWNER_NAME: kgacandole
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
    steps:
    - name: Generate GH Token
      uses: kgacandole/github_automation_scripts/.github/actions/generateGithubToken@main
    
    - name: Check Var
      if: inputs.FORCE_UPDATE == false
      uses: kgacandole/github_automation_scripts/.github/actions/checkVars@main
      with:
        repositoryName: ${{ inputs.REPOSITORY_NAME }}
        variableName: ${{ inputs.VARIABLE_NAME }}

    - name: Create Repository Variables
      id: create-repo-vars
      uses: kgacandole/github_automation_scripts/.github/actions/invokeGithubApi@main
      with:
        uriPath: "repos/${{ env.OWNER_NAME }}/${{ inputs.REPOSITORY_NAME }}/actions/variables"
        method: "POST"
        data: |
          {
            "name": "${{ inputs.VARIABLE_NAME }}",
            "value": "${{ inputs.VARIABLE_VALUE }}"
          }
        ignoreHttpStatus: '409'