name: Create Repository Secrets
run-name: Create Repository Secrets - ${{ inputs.REPOSITORY_NAME }} - ${{ inputs.VARIABLE_NAME }}
on:
  workflow_dispatch:
    inputs:      
      REPOSITORY_NAME:
        description: 'Repository Name'
        type: string
        required: true
      SECRET_NAME:
        description: 'Secret Name'
        required: true
      SECRET_VALUE:
        description: 'Secret Value'
        required: true
      

jobs:
  create-secrets:
    name: Create Secrets
    runs-on: [ubuntu-latest]
    env:
      OWNER_NAME: kgacandole
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
    steps:
    - name: Generate GH Token
      uses: kgacandole/github_automation_scripts/.github/actions/generateGithubToken@main
    
    - name: Get Key
      id: key
      uses: kgacandole/github_automation_scripts/.github/actions/invokeGithubApi@main
      with:
        uriPath: "repos/${{ env.OWNER_NAME }}/${{ inputs.REPOSITORY_NAME }}/actions/secrets/public-key"
        method: "GET"
    
    - name: Check Key
      shell: bash
      run: echo ${{ steps.key.outputs.response }}
      
