name: Create Tag
run-name: Create Tag
on:
  workflow_dispatch:
    inputs:
      OWNER_NAME:
        description: 'Owner Name'
        type: string
        required: true
      REPOSITORY_NAME:
        description: 'Repository Name'
        type: string
        required: true
      BRANCH_NAME:
        description: 'Branch Name'
        required: true
      TAG_NAME:
        description: 'Tag Name'
        required: true

jobs:
  create-tag:
    name: Create Repository Tag
    runs-on: [ubuntu-latest]
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - name: Get Commit Sha
      id: sha
      uses: kgacandole/github_automation_scripts/.github/actions/invokeGithubApi@main
      with:
        uriPath: "repos/${{ inputs.OWNER_NAME }}/${{ inputs.REPOSITORY_NAME }}/commits/${{ inputs.BRANCH_NAME }}"
        method: "GET"
    
    - name: Create Tag
      if: steps.sha.outputs.response != ''
      id: create-tag
      uses: kgacandole/github_automation_scripts/.github/actions/invokeGithubApi@main
      with:
        uriPath: "repos/${{ inputs.OWNER_NAME }}/${{ inputs.REPOSITORY_NAME }}/git/refs"
        method: "POST"
        data: |
          {
            "ref": "refs/tags/${{ inputs.TAG_NAME }}",
            "sha": "${{ fromJson(steps.sha.outputs.response).sha }}"
          }
    
    - name: Print Response
      if: steps.create-tag.outputs.status == '200'
      uses: actions/github-script@v7
      with:
        script: core.notice("Tag '${{ inputs.TAG_NAME }}' successfully created.")