name: List All Repositories
run-name: List All Repositories
on:
  workflow_dispatch:
    inputs:
      SEARCH_STRINGS:
        description: "Key words to be included in the search (separate by comma if multiple)"
        required: false
        type: string
      SKIP_STRINGS:
        description: "Key words to be excluded in the search (separate by comma if multiple)"
        required: false
        type: string

jobs:
  list-repos:
    name: List Repositories
    runs-on: [ubuntu-latest]
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      OWNER_NAME: kgacandole
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: kgacandole/github_automation_scripts
        ref: main
        path: scripts
        token: ${{ env.GH_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ vars.PYTHON_VERSION }}
    
    - name: List Repositories
      shell: bash
      run: |
        pip install requests
        python scripts/python/list_repositories.py "${{ env.GH_TOKEN }}" "100" "${{ inputs.SEARCH_STRINGS }}" "${{ inputs.SKIP_STRINGS }}" "${{ env.OWNER_NAME }}"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "repository_list"
        path: "repo_list.txt"