name: Github Generate Token
description: Github Generate Token

runs:
  using: "composite"
  steps:  
  - name: Generate GH Token
    uses: actions/create-github-app-token@v3
    id: gh-app-token
    with:
      app-id: ${{ env.GH_APP_ID }}
      private-key: ${{ env.GH_APP_PRIVATE_KEY }}
      owner: ${{ env.OWNER_NAME }}
      skip-token-revoke: true
  
  - name: Set Env Var
    uses: actions/github-script@v7
    with:
      script: core.exportVariable("GITHUB_TOKEN", "${{ steps.gh-app-token.outputs.token }}")